Repository wanted-pre-onboarding-fe-8/8oogle, pull requests merged in 2022-07, with the labels that each got.

#11 광고관리 페이지 카드 컴포넌트 구현
  src/pages/adManagement/Card.tsx
Labels: enhancement

#8 플랫폼 차트 컴포넌트 구현
  src/pages/dashboard/PlatformChart.tsx
  src/utils/constants/charts.tsx
  src/utils/helpers/charts.tsx
Labels: enhancement

#12 대시보드 매체현황 테이블 구현
  src/pages/dashboard/PlatformTable.tsx
  src/types/platform.d.ts
Labels: enhancement

#25 광고 추가/수정 폼 구현
  src/components/adForm/AdForm.tsx
  src/components/adForm/CurrencyField.tsx
  src/components/adForm/index.tsx
  src/hooks/useInput.ts
  src/utils/constants/currency.ts
  src/utils/helpers/formatters.ts
  tsconfig.json
Labels: enhancement

#31 광고관리 페이지 카드 컴포넌트 개선
  src/components/Card/CardPopover.tsx
  src/components/Card/CardTable.tsx
  src/components/Card/index.tsx
  src/pages/adManagement/Card.tsx
  src/pages/adManagement/Wrapper.tsx
Labels: refactor

#42 invalidateQueriesByName 함수 호출 시 발생하는 문제 해결
  src/queries/queryRequest.ts
Labels: bug

#34 광고 수정 페이지 구현
  src/components/Card/index.tsx
  src/components/adForm/AdForm.tsx
  src/pages/adEdit/index.tsx
  src/pages/adManagement/Card.tsx
  src/pages/dashboard/index.tsx
Labels: enhancement

#38 광고 추가 페이지 구현
  src/components/adForm/AdForm.tsx
  src/components/adForm/CurrencyField.tsx
  src/pages/adAdd/index.tsx
Labels: enhancement

#44 플랫폼 변수를 상수로 교체
  src/utils/helpers/charts.tsx
Labels: fix

#46 테이블 컴포넌트 리팩토링 및 천단위 콤마 적용
  src/pages/dashboard/PlatformTable.tsx
  src/utils/helpers/number.ts
Labels: refactor

#52 [버그]폼관련 에러 수정
  src/components/Card/CardTable.tsx
  src/components/adForm/AdForm.tsx
  src/components/adForm/CurrencyField.tsx
  src/pages/adAdd/index.tsx
  src/pages/dashboard/PlatformTable.tsx
Labels: bug
